// ISA ver 1.0: matrix shapes and byte strides travel in plena.matrix_* ops; the
// last GDMA copies O back into L2 at 12288 for the checker.
// Hand-written FlashAttention: 32 queries, head_dim 32, two KV blocks of 32.
// K arrives already transposed. This is the reference the general lowering has to
// reproduce, so it stays hand-written on purpose.
//
// Three facts it pins down.
//
// 1. The O update is diag(exp(m-m'))*O + P*V. The systolic array cannot express
//    it -- no instruction loads the accumulator and M_WRITEOUT drains and clears
//    -- so it runs on the VPU: V_MUL_SCALAR_F16 then V_ADD_F16. One extra
//    writeout plus two VPU passes over the O tile per KV block.
// 2. There is no scalar exp. The rescale exponents go through the FP16 vector
//    unit, here batched over the whole column instead of one element per row.
// 3. A VPU stream is lazy: it names an L1 range and re-reads it on every
//    consumer. P therefore lands in its own buffer. Writing P over S made the
//    later row-sum re-read the overwritten bytes and cost 25% accuracy.
module attributes {plena.stage = "target", plena.schema = 1 : i64,
                   plena.cores = 1 : i64, plena.l1_bytes = 19072 : i64,
                   plena.l2_bytes = 14336 : i64, plena.dram_bytes = 12288 : i64} {
  "plena.dma"() {direction = "load", dram = 0 : i64, l2 = 0 : i64, bytes = 10240 : i64} : () -> ()
  "plena.core_block"() ({
    "plena.instruction"() {assembly = "C_LUI_U32 15, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 2048"} : () -> ()
    "plena.instruction"() {assembly = "C_SET_DMA_BYTES 15"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 1, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 2, 0"} : () -> ()
    "plena.instruction"() {assembly = "L2_LOAD_RAW 1, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 12, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 12, 12, 2048"} : () -> ()
    plena.matrix_load {operand = "weight", element_type = "f16", address_register = 12 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    "plena.instruction"() {assembly = "C_LUI_U32 13, 0"} : () -> ()
    plena.matrix_load {operand = "activation", element_type = "f16", address_register = 13 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    plena.matrix_mma {element_type = "f16"}
    "plena.instruction"() {assembly = "C_LUI_U32 12, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 12, 12, 2048"} : () -> ()
    plena.matrix_writeout {element_type = "f16", address_register = 12 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    "plena.instruction"() {assembly = "C_WAIT_MATRIX"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_SET_VECTOR_ELEMENTS 15"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 1, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 2048"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 2, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 2048"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 3, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 3, 3, 2176"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 6, 3"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 14, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 14, 14, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_BEGIN 14"} : () -> ()
    "plena.instruction"() {assembly = "V_LOAD_F16 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_REDUCE_MAX_F16_F32 0, 0"} : () -> ()
    "plena.instruction"() {assembly = "S_STORE_F32 2, 0"} : () -> ()
    "plena.instruction"() {assembly = "V_SUB_SCALAR_F16 1, 0, 0"} : () -> ()
    "plena.instruction"() {assembly = "V_EXP_F16 2, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_REDUCE_SUM_F16_F32 1, 2"} : () -> ()
    "plena.instruction"() {assembly = "S_STORE_F32 3, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_STORE_F16 6, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 64"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 3, 3, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 6, 6, 64"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_END"} : () -> ()
    "plena.instruction"() {assembly = "C_WAIT_VPU"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 12, 1"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 12, 12, 2048"} : () -> ()
    plena.matrix_load {operand = "weight", element_type = "f16", address_register = 12 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    "plena.instruction"() {assembly = "C_LUI_U32 13, 3"} : () -> ()
    plena.matrix_load {operand = "activation", element_type = "f16", address_register = 13 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    plena.matrix_mma {element_type = "f16"}
    "plena.instruction"() {assembly = "C_LUI_U32 12, 3"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 12, 12, 2048"} : () -> ()
    plena.matrix_writeout {element_type = "f16", address_register = 12 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    "plena.instruction"() {assembly = "C_WAIT_MATRIX"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 12, 1"} : () -> ()
    plena.matrix_load {operand = "weight", element_type = "f16", address_register = 12 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    "plena.instruction"() {assembly = "C_LUI_U32 13, 0"} : () -> ()
    plena.matrix_load {operand = "activation", element_type = "f16", address_register = 13 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    plena.matrix_mma {element_type = "f16"}
    "plena.instruction"() {assembly = "C_LUI_U32 12, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 12, 12, 2048"} : () -> ()
    plena.matrix_writeout {element_type = "f16", address_register = 12 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    "plena.instruction"() {assembly = "C_WAIT_MATRIX"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_SET_VECTOR_ELEMENTS 15"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 1, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 2048"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 2, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 2048"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 4, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 4, 4, 2304"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 5, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 5, 5, 2560"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 6, 3"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 14, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 14, 14, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_BEGIN 14"} : () -> ()
    "plena.instruction"() {assembly = "V_LOAD_F16 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_REDUCE_MAX_F16_F32 0, 0"} : () -> ()
    "plena.instruction"() {assembly = "S_LOAD_F32 1, 2"} : () -> ()
    "plena.instruction"() {assembly = "S_MAX_F32 2, 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "S_STORE_F32 2, 2"} : () -> ()
    "plena.instruction"() {assembly = "S_SUB_F32 3, 1, 2"} : () -> ()
    "plena.instruction"() {assembly = "S_STORE_F32 4, 3"} : () -> ()
    "plena.instruction"() {assembly = "V_SUB_SCALAR_F16 1, 0, 2"} : () -> ()
    "plena.instruction"() {assembly = "V_EXP_F16 2, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_REDUCE_SUM_F16_F32 4, 2"} : () -> ()
    "plena.instruction"() {assembly = "S_STORE_F32 5, 4"} : () -> ()
    "plena.instruction"() {assembly = "V_STORE_F16 6, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 64"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 4, 4, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 5, 5, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 6, 6, 64"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_END"} : () -> ()
    "plena.instruction"() {assembly = "C_WAIT_VPU"} : () -> ()
    // 32 FP32 row statistics exceed one 512-bit register (16 FP32): two halves.
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 16"} : () -> ()
    "plena.instruction"() {assembly = "C_SET_VECTOR_ELEMENTS 15"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 1, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 2304"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 2, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 2432"} : () -> ()
    "plena.instruction"() {assembly = "V_LOAD_F32 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_CAST_F32_F16 1, 0"} : () -> ()
    "plena.instruction"() {assembly = "V_EXP_F16 2, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_CAST_F16_F32 3, 2"} : () -> ()
    "plena.instruction"() {assembly = "V_STORE_F32 2, 3"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 64"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 64"} : () -> ()
    "plena.instruction"() {assembly = "V_LOAD_F32 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_CAST_F32_F16 1, 0"} : () -> ()
    "plena.instruction"() {assembly = "V_EXP_F16 2, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_CAST_F16_F32 3, 2"} : () -> ()
    "plena.instruction"() {assembly = "V_STORE_F32 2, 3"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_SET_VECTOR_ELEMENTS 15"} : () -> ()
    "plena.instruction"() {assembly = "C_WAIT_VPU"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 1, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 2432"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 2, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 2176"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 3, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 3, 3, 2560"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 14, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 14, 14, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_BEGIN 14"} : () -> ()
    "plena.instruction"() {assembly = "S_LOAD_F32 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "S_LOAD_F32 1, 2"} : () -> ()
    "plena.instruction"() {assembly = "S_MUL_F32 2, 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "S_LOAD_F32 3, 3"} : () -> ()
    "plena.instruction"() {assembly = "S_ADD_F32 4, 2, 3"} : () -> ()
    "plena.instruction"() {assembly = "S_STORE_F32 2, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 3, 3, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_END"} : () -> ()
    "plena.instruction"() {assembly = "C_WAIT_VPU"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 12, 2"} : () -> ()
    plena.matrix_load {operand = "weight", element_type = "f16", address_register = 12 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    "plena.instruction"() {assembly = "C_LUI_U32 13, 3"} : () -> ()
    plena.matrix_load {operand = "activation", element_type = "f16", address_register = 13 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    plena.matrix_mma {element_type = "f16"}
    "plena.instruction"() {assembly = "C_LUI_U32 12, 4"} : () -> ()
    plena.matrix_writeout {element_type = "f16", address_register = 12 : i64, rows = 32 : i64, columns = 32 : i64, stride_bytes = 64 : i64}
    "plena.instruction"() {assembly = "C_WAIT_MATRIX"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_SET_VECTOR_ELEMENTS 15"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 1, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 2432"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 2, 3"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 2048"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 3, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 14, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 14, 14, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_BEGIN 14"} : () -> ()
    "plena.instruction"() {assembly = "S_LOAD_F32 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_LOAD_F16 0, 2"} : () -> ()
    "plena.instruction"() {assembly = "V_MUL_SCALAR_F16 1, 0, 0"} : () -> ()
    "plena.instruction"() {assembly = "V_LOAD_F16 2, 3"} : () -> ()
    "plena.instruction"() {assembly = "V_ADD_F16 3, 1, 2"} : () -> ()
    "plena.instruction"() {assembly = "V_STORE_F16 2, 3"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 64"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 3, 3, 64"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_END"} : () -> ()
    "plena.instruction"() {assembly = "C_WAIT_VPU"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_SET_VECTOR_ELEMENTS 15"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 1, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 2176"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 2, 3"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 2048"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 14, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 14, 14, 32"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_BEGIN 14"} : () -> ()
    "plena.instruction"() {assembly = "S_LOAD_F32 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "S_RCP_F32 1, 0"} : () -> ()
    "plena.instruction"() {assembly = "V_LOAD_F16 0, 2"} : () -> ()
    "plena.instruction"() {assembly = "V_MUL_SCALAR_F16 1, 0, 1"} : () -> ()
    "plena.instruction"() {assembly = "V_STORE_F16 2, 1"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 4"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 64"} : () -> ()
    "plena.instruction"() {assembly = "C_LOOP_END"} : () -> ()
    "plena.instruction"() {assembly = "C_WAIT_VPU"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 15, 0"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 15, 15, 2048"} : () -> ()
    "plena.instruction"() {assembly = "C_SET_DMA_BYTES 15"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 1, 3"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 1, 1, 2048"} : () -> ()
    "plena.instruction"() {assembly = "C_LUI_U32 2, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_ADDI_U32 2, 2, 2048"} : () -> ()
    "plena.instruction"() {assembly = "L2_STORE_RAW 1, 2"} : () -> ()
    "plena.instruction"() {assembly = "C_FENCE_ALL"} : () -> ()
  }) {core = 0 : i64, reads = array<i64: 0, 10240>, writes = array<i64: 10240, 2048>} : () -> ()
  "plena.dma"() {direction = "store", dram = 10240 : i64, l2 = 10240 : i64, bytes = 2048 : i64} : () -> ()
  "plena.dma"() {direction = "load", dram = 10240 : i64, l2 = 12288 : i64, bytes = 2048 : i64} : () -> ()
}
